### ISSUE TITLE
Unclear which differences apply to which vault

### ISSUE THREAD

**Issue by MikeTheCanuck** [jhaals/ansible-vault#10]
I'm evaluating the use of these two vaults for use by an infrastructure team in an open source project.

It's unclear to me which difference/advantage applies to which vault in the section "What's the difference between ansible-vault and hashi_vault", and this is valuable information for an evaluation like mine.  

Here are my guesses - if you can confirm, I'll submit a PR to clarify the README:
- (Ansible Vault) No external dependencies. (hashi_vault) requires hvac
- (Hashi Vault) Uses the same environment variables as vault itself
- (Hashi Vault) Quicker update cycle [because it doesn't depend on core Ansible release cycle]
- (Hashi Vault) Supports dynamic secrets
- (Hashi Vault) Supports custom fields

Thanks!

**Comment by jhaals** [comment]
Hi Mike.

All of them apply to `ansible-vault`. Things that the hashi_vault module does not support when I compared them earlier. 

So to make things clear

(Ansible Vault) No external dependencies. (hashi_vault) requires hvac
(Ansible Vault) Uses the same environment variables as vault itself
(Ansible Vault) Quicker update cycle [because it doesn't depend on core Ansible release cycle](Ansible Vault) Supports dynamic secrets
(Ansible Vault) Supports custom fields
